title: Google Earth Engine with Xarray and Dask
author: Pulakesh Pradhan
execute:
  execute_notebooks: off
html:
  use_issues_button: true
  use_repository_button: true
repository:
  url: https://github.com/pulakeshpradhan/gee
  branch: main
